import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable, map } from 'rxjs';
import { API_BASE_URL } from '../../api.config';
import { Difficulty, TourLogInterface } from './tour-log-interface';

interface TourLogApiResponse { // backend API response format
  id: string;
  tourId: string;
  timeStamp: string;
  comment?: string;
  difficulty?: Difficulty | number | string;
  totalDistance?: number;
  totalTime?: number;
  rating?: number;
}

export type CreateTourLogRequest = Omit<TourLogInterface, 'id'>; // request format for creating new tour log, excluding id which is generated by the backend
export type UpdateTourLogRequest = Omit<TourLogInterface, 'id' | 'tourId'>; // request format for updating  tour log,  id and tourId not updatable

@Injectable({
  providedIn: 'root',
})
export class TourLogService {
  private readonly baseTourLogUrl = `${API_BASE_URL}/tourlogs`; // http service

  constructor(private readonly http: HttpClient) {}

  getLogsByTourId(tourId: string): Observable<TourLogInterface[]> { 
    return this.http
      .get<TourLogApiResponse[]>(`${this.baseTourLogUrl}/tour/${tourId}`)
      .pipe(map((logs) => logs.map((log) => this.toTourLog(log))));
  }

  getLog(id: string): Observable<TourLogInterface> { // 
    return this.http
      .get<TourLogApiResponse>(`${this.baseTourLogUrl}/${id}`)
      .pipe(map((log) => this.toTourLog(log)));
  }

  createLog(log: CreateTourLogRequest): Observable<TourLogInterface> {
    return this.http
      .post<TourLogApiResponse>(this.baseTourLogUrl, this.toApiRequest(log))
      .pipe(map((createdLog) => this.toTourLog(createdLog)));
  }

  updateLog(id: string, log: UpdateTourLogRequest): Observable<void> {
    return this.http.put<void>(`${this.baseTourLogUrl}/${id}`, this.toApiRequest(log));
  }

  deleteLog(id: string): Observable<void> {
    return this.http.delete<void>(`${this.baseTourLogUrl}/${id}`);
  }

  private toTourLog(response: TourLogApiResponse): TourLogInterface { // maps the API response to the TourLogInterface, converting timestamp to Date object, and mapping the difficulty to the UI representation
    return {
      id: response.id,
      tourId: response.tourId,
      timeStamp: new Date(response.timeStamp),
      comment: response.comment,
      difficulty: this.toUiDifficulty(response.difficulty),
      totalDistance: response.totalDistance,
      totalTime: response.totalTime,
      rating: response.rating,
    };
  }

  private toApiRequest(log: CreateTourLogRequest | UpdateTourLogRequest) { // maps TourLogInterface to the API request format, converting timestamp to ISO string and mapping difficulty to the API representation
    return {
      ...log,
      timeStamp: log.timeStamp.toISOString(),
      difficulty: this.toApiDifficulty(log.difficulty),
    };
  }

  private toApiDifficulty(difficulty?: Difficulty): number | undefined { // maps UI difficulty to API representation
    if (!difficulty) return undefined;

    return {
      [Difficulty.Easy]: 0,
      [Difficulty.Medium]: 1,
      [Difficulty.Hard]: 2,
    }[difficulty];
  }

  private toUiDifficulty(difficulty?: Difficulty | number | string): Difficulty | undefined { // maps API difficulty to UI representation
    if (difficulty === undefined || difficulty === null) return undefined;

    if (typeof difficulty === 'number') {
      return [Difficulty.Easy, Difficulty.Medium, Difficulty.Hard][difficulty];
    }

    const normalized = difficulty.toString().toLowerCase();
    if (normalized === 'easy') return Difficulty.Easy;
    if (normalized === 'medium') return Difficulty.Medium;
    if (normalized === 'hard') return Difficulty.Hard;

    return undefined;
  }
}
