<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <!-- <Compile Include="TourPlanner.Bll" />
    <Compile Include="TourPlanner.Dal" />
    <Compile Include="TourPlanner.Models" />
    <Compile Include="TourPlanner.Tests" /> -->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TourPlanner.Models\TourPlanner.Models.csproj" />
    <ProjectReference Include="..\TourPlanner.Bll\TourPlanner.Bll.csproj" />
  </ItemGroup>

</Project>
